# netlify.toml

# Settings for Netlify Functions
[functions]
  # Specifies the directory where Netlify should look for serverless functions.
  directory = "netlify/functions"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Build settings if needed (adjust command/directory if different)
# [build]
#   command = "npm run build" # Or your specific build command
#   publish = "dist"          # Or your specific publish directory
