# netlify.toml

# Settings for Netlify Functions
[functions]
  # Specifies the directory where Netlify should look for serverless functions.
  directory = "netlify/functions"
  # Increase timeout for image processing functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[functions.gemini-call]
  timeout = 60  # Increased to maximum allowed 60 seconds
  node_bundler = "esbuild"
  
[functions.gemini-describe-object]
  timeout = 60  # Increased to maximum allowed 60 seconds
  node_bundler = "esbuild"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Build settings if needed (adjust command/directory if different)
# [build]
#   command = "npm run build" # Or your specific build command
#   publish = "dist"          # Or your specific publish directory
