# netlify.toml

# Directory for all Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Per-function settings
[functions.gemini-call]
  timeout = 60  # Max timeout allowed by Netlify
  node_bundler = "esbuild"

[functions.gemini-describe-object]
  timeout = 60  # Max timeout allowed by Netlify
  node_bundler = "esbuild"

# SPA fallback (for client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Build settings
# Uncomment and customize if needed
# [build]
#   command = "npm run build"
#   publish = "dist"
